INSERT INTO Race (created, lastUpdated, startTime, finished) VALUES (now(), now(), NULL, 0);

INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anna', 'Ochsner', 1, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kasper', 'Pryds', 2, NULL, 32, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Christina', 'Jørgensen', 3, NULL, 35, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Tim', 'Bonde', 4, NULL, 39, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Malene', 'Hansen', 5, NULL, 37, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Bastian', 'Bonde', 6, NULL, 8, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kristian Martin', 'Søndergaard', 7, NULL, 34, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kristina', 'Filbert', 8, NULL, 29, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Randi', 'Boesen', 9, NULL, 54, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hanne', 'Saxgreen', 10, NULL, 60, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Betina Dehlendorff', 'Nielsen', 11, NULL, 30, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jens', 'Wørzner', 12, NULL, 58, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Gitte', 'Karlshøj', 13, NULL, 58, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Victor', 'Gustin', 14, NULL, 9, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Philip', 'Gustin', 15, NULL, 6, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Stephan', 'Gustin', 16, NULL, 42, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Asta', 'Breining', 17, NULL, 8, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sanni N.', 'Breining', 18, NULL, 32, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anders Krogh', 'Møller', 19, NULL, 41, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Bertil Krogh', 'Møller', 20, NULL, 8, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Johan Krogh', 'Møller', 21, NULL, 6, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Merete', 'Borghammer', 22, NULL, 40, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kjeld', 'Mogensen', 23, NULL, 49, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Markus', 'Stephanell', 24, NULL, 26, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Esben', 'Yates', 25, NULL, 37, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Andrea', 'Yates', 26, NULL, 8, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sigurd', 'Yates', 27, NULL, 7, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Leopold', 'Yates', 28, NULL, 4, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Dicte', 'Olsen', 29, NULL, 10, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Asger', 'Olsen', 30, NULL, 13, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Morten', 'Olsen', 31, NULL, 41, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jette', 'Riis', 32, NULL, 45, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jakob', 'Worm', 33, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Line', 'Hviid', 34, NULL, 36, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jeppe Viborg', 'Hviid', 35, NULL, 37, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anders', 'Frølund', 36, NULL, 57, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Stine', 'Norskov', 37, NULL, 28, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Rasmus', 'Sørensen', 38, NULL, 29, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Lærke Norskov', 'Stokholm', 39, NULL, 13, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Amalie Norskov', 'Stokholm', 40, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'August', 'Kramshøj', 41, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Carl-Emil', 'Kramshøj', 42, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Thomas', 'Kramshøj', 43, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Henrik', 'Hoffman', 44, NULL, 53, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Johanne', 'Lyngsø', 45, NULL, 9, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Thomas', 'Lyngsø', 46, NULL, 50, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jette', 'Lyngsø', 47, NULL, 47, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Trine Dam', 'Junker', 48, NULL, 66, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Lars', 'Kvist', 49, NULL, 57, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Rasmus', 'Kvist', 50, NULL, 12, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anette', 'Lysgaard', 51, NULL, 48, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hanne-Grethe', 'Christensen', 52, NULL, 71, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jonas Olesen', 'Bundgaard', 53, NULL, 13, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Lotte Olesen', 'Bundgaard', 54, NULL, 41, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Margrethe', 'Grønbech', 55, NULL, 10, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Johannes', 'Grønbech', 56, NULL, 5, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Gustav', 'Grønbech', 57, NULL, 8, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Karina Grønbech', 'Andresen', 58, NULL, 42, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Svea', 'Friis', 59, NULL, 9, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Malthe', 'Friis', 60, NULL, 6, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Rasmus', 'Friis', 61, NULL, 38, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jenny', 'Friis', 62, NULL, 38, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Malou', 'Trolle', 63, NULL, 10, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Allan', 'Trolle', 64, NULL, 46, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Elias', 'Trolle', 65, NULL, 13, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Peter Lund', 'Hansen', 66, NULL, 10, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hanne Lund', 'Hansen', 67, NULL, 46, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Casper', 'Sølvsten', 68, NULL, 14, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Cille', 'Sølvsten', 69, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Johanna Gubi', 'Axelsen', 70, NULL, 12, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Søren Gubi', 'Axelsen', 71, NULL, 42, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hjalte Gubi', 'Axelsen', 72, NULL, 11, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Ester Wowk', 'Vestergaard', 73, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Laurits Wowk', 'Vestergaard', 74, NULL, 8, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anna Wowk', 'Vestergaard', 75, NULL, 37, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Astrid', 'Andreassen', 76, NULL, 37, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sidsel Nørgaard', 'Pedersen', 77, NULL, 38, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sune Brinch', 'Erichsen', 78, NULL, 31, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Luise', 'Friis', 79, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Asger', 'Friis', 80, NULL, 15, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Alexander', 'Lang', 81, NULL, 14, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Connie', 'Bang', 82, NULL, 44, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Frida Bang', 'Larsen', 83, NULL, 12, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Arthur Trier', 'Sørensen', 84, NULL, 9, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Laust Trier', 'Sørensen', 85, NULL, 41, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Thomas', 'Norskov', 86, NULL, 6, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Nanna', 'Norskov', 87, NULL, 8, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kathrine', 'Kofoed', 88, NULL, 36, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Clara Grøndal', 'Ubbesen', 89, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kasper', 'Brinck', 90, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Einar', 'Brinck', 91, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jens', 'Høgild', 92, NULL, 11, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Karsten', 'Høgild', 93, NULL, 43, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anders Thorsted', 'Mahler', 94, NULL, 9, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Birgitte Thorsted', 'Mahler', 95, NULL, 43, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anne Thorsted', 'Mahler', 96, NULL, 7, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jakob', 'Sandahl', 97, NULL, 9, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anne Sofie', 'Sandahl', 98, NULL, 12, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hanne Lund', 'Snedker', 99, NULL, 45, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Peter', 'Wistoft', 100, NULL, 53, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Helle Nedergaard', 'Wistoft', 101, NULL, 54, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Maggie', 'Olivier', 102, NULL, 24, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Lene', 'Olivier', 103, NULL, 52, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Thomas', 'Smidt-Kjærby', 104, NULL, 40, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Pelle', 'Smidt-Kjærby', 105, NULL, 8, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Filippa Mia', 'Smidt-Kjærby', 106, NULL, 5, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sarah Birkegaard', 'Rasmussen', 107, NULL, 13, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Nana', 'Frandsen', 108, NULL, 12, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Lene', 'Rode', 109, NULL, 45, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Rosa', 'Rode', 110, NULL, 9, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Bjarke Nygaard', 'Løvind', 111, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Svante Nygaard', 'Løvind', 112, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Asta Grøndal', 'Ubbesen', 113, NULL, 8, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Henriette', 'Grønbech', 114, NULL, 41, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jesper Kjær', 'Ries', 115, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kristine Kjær', 'Ries', 116, NULL, 100, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'William Kjær', 'Ries', 117, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Karoline Kjær', 'Ries', 118, NULL, 100, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Cille', 'Borghammer', 119, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Anja Smidt', 'Nielsen', 120, NULL, 45, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Christoffer', 'Mørk', 121, NULL, 100, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Gowry', 'Mørk', 122, NULL, 100, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Luna', 'Mørk', 123, NULL, 100, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sylvia', 'Gahl', 124, NULL, 13, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Lovisa', 'Gahl', 125, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Leif', 'Petersson', 126, NULL, 56, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Inge', 'Schou-Hansen', 127, NULL, 11, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Ludvig', 'Schou-Hansen', 128, NULL, 14, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Frederik', 'Schou-Hansen', 129, NULL, 43, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Martha', 'Mandrup-Specht', 130, NULL, 8, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hjalte', 'Mandrup-Specht', 131, NULL, 7, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Sarah R E', 'Krämer', 132, NULL, 9, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Mads Ole', 'Sørensen', 133, NULL, 42, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Ruth Smidt', 'Nielsen', 134, NULL, 100, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jonas Dahl', 'Knudsen', 135, NULL, 43, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Karl-Emil', 'Dalbach', 136, NULL, 11, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Morten', 'Gleerup', 137, NULL, 42, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Michael', 'Højholdt', 138, NULL, 43, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Julius Sjøberg', 'Vind', 139, NULL, 10, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Kasper', 'Kappel', 140, NULL, 36, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Bastian', 'Valentin', 141, NULL, 27, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Line', 'Mygind', 142, NULL, 31, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Elvira', 'Eriksen', 143, NULL, 9, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Søren', 'Thorsen', 144, NULL, 39, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Maria', 'Houe', 145, NULL, 35, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Jonas Houe', 'Thorsen', 146, NULL, 7, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Hector Houe', 'Thorsen', 147, NULL, 9, 'MALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Eva Borchorst', 'Mejnertz', 148, NULL, 37, 'FEMALE');
INSERT INTO Runner (created, lastUpdated, firstName, lastName, runnerNumber, email, age, gender) VALUES (now(), now(), 'Nikolaj Gandrup', 'Borchorst', 149, NULL, 9, 'MALE');
